### PR TITLE
Favor spaces over tabs

### PR DESCRIPTION
**Pull request by jessieay**
* Beginning of WWIII, or simple PR? You decide!

### CODE REVIEW

**Comment by pkarman** [comment]
SPACES FTW!!

**Comment by monfresh** [comment]
Spaces, mos def!

**Comment by monfresh** [comment]
What do you think about adding a section to our development guide about text editors and recommending that everyone install a plugin that automatically removes extra whitespace, and replaces tabs with spaces?

**Comment by jessieay** [comment]
@monfresh great idea! Was just chatting with someone over lunch about this.

**Pull request merged**
