### PR TITLE
Adding methods to the guides navigation

### PR DESCRIPTION
**Pull request by wslack**
Adds the methods guide as "design methods cards" for additional context when doing menu navigation on the Guides page. Unsure if that's the right nomenclature....

@jenniferthibault please feel free to mod

### CODE REVIEW

**Comment by jenniferthibault** [comment]
What's the best practice for editing this post-merge? Using "Design Methods" is more consistent w/ the titling we've been using. Should I make a new branch & PR? (Sincerely, a GitHub best practice n00b just trying to Do The Right Thing)

**Comment by wslack** [comment]
@mbland it looks like Jen had some comments. Should I revert above or is the better action (cleaner github history) to do a brand-new one? I would think reverting....but I don't know what happens with a branch in that instance.

**Comment by mbland** [comment]
In this case, I wouldn't bother reverting. @jenniferthibault you can use [the GitHub editing interface](https://github.com/18F/guides/edit/18f-pages/index.html) to make a new change, and select the "Create a **new branch** for this commit and start a pull request." option in the **Commit changes** box when you're done.

**Comment by jenniferthibault** [comment]
Neato!! (Yes, I said "neato" and really meant it) I'm on it now, thank you @mbland for the next steps and @wslack for the PR and process clarification

**Pull request merged**
